<a href="https://colab.research.google.com/github/Anastasia-front/data-science/blob/main/intro_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectors & Matrix

In [20]:
import numpy as np

vector = np.arange(1, 11)
print("First vector (first 10 natural numbers):", vector)

First vector (first 10 natural numbers): [ 1  2  3  4  5  6  7  8  9 10]


In [21]:
matrix_zeros = np.zeros((3, 3))
print("\nSecond vector (3x3 matrix with zeros):")
print(matrix_zeros)


Second vector (3x3 matrix with zeros):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
matrix_random_int = np.random.randint(1, 11, size=(5, 5))
print("\nThird vector (5x5 matrix with random integers):")
print(matrix_random_int)


Third vector (5x5 matrix with random integers):
[[ 3  2 10  4  8]
 [ 9  8  1  2  9]
 [ 8  3  3  6  2]
 [ 8  7  7  4  2]
 [ 6  5  7  9  1]]


In [23]:
matrix_random_float = np.random.rand(4, 4)
print("\nFourth vector (4x4 matrix with random floating-point numbers):")
print(matrix_random_float)


Fourth vector (4x4 matrix with random floating-point numbers):
[[0.48252355 0.95921108 0.67691046 0.59894115]
 [0.85144913 0.9723557  0.46968542 0.40305487]
 [0.09706429 0.14899314 0.63011531 0.98939372]
 [0.88906007 0.95563846 0.57212784 0.91690118]]


In [24]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)



Addition: [ 9  8  6  7 11]
Subtraction: [-1  4 -2 -1  5]
Multiplication: [20 12  8 12 24]


In [25]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)
print("\nDot product of two vectors:", dot_product)


Dot product of two vectors: 1.8677478997470813


In [26]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix1, matrix2)
print("\nMatrix product:")
print(matrix_product)


Matrix product:
[[ 42  84 120]
 [ 51  91 130]]


In [27]:
matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
try:
    inverse_matrix = np.linalg.inv(matrix_3x3)
    print("\nInverse matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nInverse matrix does not exist.")


Inverse matrix:
[[ 0.09090909  0.1        -0.21818182]
 [-0.18181818  0.5        -0.36363636]
 [ 0.09090909 -0.3         0.38181818]]


In [28]:
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix_4x4)
print("\nTransposed matrix:")
print(transposed_matrix)


Transposed matrix:
[[0.91128383 0.94800557 0.86944934 0.2881611 ]
 [0.27110867 0.69537835 0.1262569  0.31695899]
 [0.42466523 0.06411742 0.79978562 0.87269479]
 [0.10568087 0.58209778 0.90715054 0.03777   ]]


In [29]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
matrix_vector_product = np.dot(matrix_3x4, vector_4)
print("\nMatrix-vector product:")
print(matrix_vector_product)


Matrix-vector product:
[66 75 69]


In [30]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
matrix_vector_product_2 = np.dot(matrix_2x3, vector_3)
print("\nMatrix-vector product:")
print(matrix_vector_product_2)


Matrix-vector product:
[0.77314371 1.09005879]


In [31]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
elementwise_multiplication = np.multiply(matrix1, matrix2)
print("\nElement-wise multiplication:")
print(elementwise_multiplication)


Element-wise multiplication:
[[90 70]
 [15 42]]


In [32]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.dot(matrix1, matrix2)
print("\nMatrix product:")
print(matrix_product)


Matrix product:
[[49 80]
 [57 76]]


In [33]:
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))
matrix_sum = np.sum(matrix_5x5)
print("\nSum of matrix elements:", matrix_sum)


Sum of matrix elements: 1161


In [34]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
matrix_difference = matrix1 - matrix2
print("\nMatrix difference:")
print(matrix_difference)


Matrix difference:
[[ 3  5 -3 -2]
 [-5 -3  4  3]
 [-7  4 -2  5]
 [-2  4  1  4]]


In [35]:
matrix_3x3 = np.random.rand(3, 3)
row_sum_vector = np.sum(matrix_3x3, axis=1)
print("\nRow sum vector:")
print(row_sum_vector)


Row sum vector:
[2.28633803 2.11907358 0.46603608]


In [36]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix_3x4)
print("\nMatrix with squares of elements:")
print(squared_matrix)


Matrix with squares of elements:
[[  9  81  49 100]
 [ 16   1   9   4]
 [  4  25 100  81]]


In [37]:
vector = np.random.randint(1, 51, size=4)
square_root_vector = np.sqrt(vector)
print("\nVector with square roots of elements:")
print(square_root_vector)


Vector with square roots of elements:
[7.         5.56776436 5.47722558 6.63324958]


# Additional tasks

In [38]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("Task 1: Replace odd numbers with -1 in the array:", arr)

Task 1: Replace odd numbers with -1 in the array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [39]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, -1)
print("\nTask 2: Create and reshape a 1D array into a 2D array with 2 rows:\n", arr_2d)


Task 2: Create and reshape a 1D array into a 2D array with 2 rows:
 [[1 2 3]
 [4 5 6]]


In [40]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
combined = np.concatenate((a, b), axis=0)
print("\nTask 3: Stack two 2D arrays vertically:\n", combined)


Task 3: Stack two 2D arrays vertically:
 [[1 2]
 [3 4]
 [5 6]]


In [41]:
a = np.array([1, 2, 3])
output = np.repeat(a, 3)
print("\nTask 4: Repeat each element of the input array 3 times:\n", output)


Task 4: Repeat each element of the input array 3 times:
 [1 1 1 2 2 2 3 3 3]


In [42]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(a, b)
print("\nTask 5: Find common elements between two arrays:\n", common_elements)


Task 5: Find common elements between two arrays:
 [2 4]


In [43]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
indices_max5 = np.argsort(a)[-5:]
print("\nTask 6: Find indices of the first 5 maximum values in the array:\n", indices_max5)


Task 6: Find indices of the first 5 maximum values in the array:
 [18  7  3 10 15]


In [44]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a = a[~np.isnan(a)]
print("\nTask 7: Remove NaN values from a 1D array:\n", a)


Task 7: Remove NaN values from a 1D array:
 [1. 2. 3. 5. 6. 7.]


In [45]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
distance = np.linalg.norm(a - b)
print("\nTask 8: Calculate the Euclidean distance between two arrays:\n", distance)


Task 8: Calculate the Euclidean distance between two arrays:
 6.708203932499369


In [46]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index_5th_occurrence = np.where(x == 1)[0][4]
print("\nTask 9: Find the index of the 5th occurrence of the number 1 in the array:\n", index_5th_occurrence)


Task 9: Find the index of the 5th occurrence of the number 1 in the array:
 8


In [47]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
result = np.full_like(a, False)
unique_values, counts = np.unique(a, return_counts=True)
duplicates = unique_values[counts > 1]
for val in duplicates:
    result[np.where(a == val)[0][1:]] = True
print("\nTask 10: Mark repeated occurrences (from the 2nd occurrence onward) in the array as True:\n", result)


Task 10: Mark repeated occurrences (from the 2nd occurrence onward) in the array as True:
 [0 1 0 1 0 0 1 1 1 1]
